In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

# Regression Models
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [5]:
df = pd.read_csv("visa_dataset_1000.csv")

In [6]:
df

,age,annual_income,education_level,work_experience,visa_type,country,documents_complete,interview_score,previous_visa_rejection,visa_status,processing_time_days
0,24,52605,Bachelors,10,Student,UK,No,2,Yes,Rejected,34
1,37,45080,High School,4,Tourist,India,Yes,8,No,Approved,32
2,46,43088,PhD,7,Work,UK,Yes,7,No,Approved,24
3,32,18216,Masters,5,Tourist,Canada,Yes,7,No,Approved,33
4,28,40547,PhD,7,Student,USA,Yes,8,No,Approved,26
...,...,...,...,...,...,...,...,...,...,...,...
995,22,31172,PhD,1,Work,Germany,No,3,Yes,Rejected,32
996,26,47874,Bachelors,5,Work,Germany,Yes,2,No,Rejected,49
997,21,12657,PhD,2,Tourist,USA,No,7,Yes,Rejected,39
998,49,23850,High School,11,Work,Canada,Yes,9,No,Approved,32
999,44,30425,PhD,11,Student,USA,No,1,No,Rejected,39

In [7]:
df.shape

(1000, 11)

In [8]:
df_encoded = pd.get_dummies(df, drop_first=True)

df_encoded.head()

,age,annual_income,work_experience,interview_score,processing_time_days,education_level_High School,education_level_Masters,education_level_PhD,visa_type_Tourist,visa_type_Work,country_Canada,country_Germany,country_India,country_UK,country_USA,documents_complete_Yes,previous_visa_rejection_Yes,visa_status_Rejected
0,24,52605,10,2,34,False,False,False,False,False,False,False,False,True,False,False,True,True
1,37,45080,4,8,32,True,False,False,True,False,False,False,True,False,False,True,False,False
2,46,43088,7,7,24,False,False,True,False,True,False,False,False,True,False,True,False,False
3,32,18216,5,7,33,False,True,False,True,False,True,False,False,False,False,True,False,False
4,28,40547,7,8,26,False,False,True,False,False,False,False,False,False,True,True,False,False

In [9]:
X = df_encoded.drop("processing_time_days", axis=1)

y = df_encoded["processing_time_days"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
lin_model = LinearRegression()

lin_model.fit(X_train, y_train)

y_pred_lr = lin_model.predict(X_test)

In [12]:
mse = mean_squared_error(y_test, y_pred_lr)

rmse = np.sqrt(mse)

mae = mean_absolute_error(y_test, y_pred_lr)

print("Linear Regression Results")
print("MSE:", mse)
print("RMSE:", rmse)
print("MAE:", mae)

Linear Regression Results
MSE: 71.09228799662394
RMSE: 8.431624279854027
MAE: 7.360154522001777

In [13]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

In [14]:
mse_rf = mean_squared_error(y_test, y_pred_rf)

rmse_rf = np.sqrt(mse_rf)

mae_rf = mean_absolute_error(y_test, y_pred_rf)

print("Random Forest Results")
print("MSE:", mse_rf)
print("RMSE:", rmse_rf)
print("MAE:", mae_rf)

Random Forest Results
MSE: 75.313502
RMSE: 8.678335209013305
MAE: 7.3639

In [15]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "MSE": [mse, mse_rf],
    "RMSE": [rmse, rmse_rf],
    "MAE": [mae, mae_rf]
})

results

               Model        MSE      RMSE       MAE
0  Linear Regression  71.092288  8.431624  7.360155
1      Random Forest  75.313502  8.678335  7.363900

In [16]:
best_model = results.loc[results["RMSE"].idxmin()]

print("Best Model:")
print(best_model)

Best Model:
Model    Linear Regression
MSE              71.092288
RMSE              8.431624
MAE               7.360155
Name: 0, dtype: object